'use strict';

const fs = require('fs');
const path = require('path');

const DEFAULT_WASM_DIR = path.resolve(__dirname, '..', 'wasm');
const DEFAULT_SCHEMA = 'luna_pinyin';

const SCHEMA_PATCH = (schema) =>
  `# auto-generated by rime-api\npatch:\n  schema_list:\n    - schema: ${schema}\n`;

function makeFakeXHR() {
  return class FakeXHR {
    open(method, url, async) {
      this._url = url;
      this.status = 0;
      this.response = null;
    }
    set onprogress(fn) { this._op = fn; }
    set onerror(fn) { this._oe = fn; }
    set onload(fn) { this._ol = fn; }
    set onreadystatechange(fn) { this._ors = fn; }
    send() {
      try {
        const buf = fs.readFileSync(this._url);
        this.status = 200;
        this.response = new Uint8Array(buf).buffer;
        this.readyState = 4;
        if (this._ors) this._ors({});
        if (this._ol) this._ol({ target: this });
      } catch (e) {
        this.status = 404;
        if (this._oe) this._oe(e);
        else throw e;
      }
    }
  };
}

class Rime {
  constructor(options = {}) {
    this.wasmDir = path.resolve(options.wasmDir || DEFAULT_WASM_DIR);
    this.schema = options.schema || DEFAULT_SCHEMA;
    this.verbose = !!options.verbose;
    this._enc = new TextEncoder();
    this._module = null;
    this._ready = false;
    this._queue = Promise.resolve();
  }

  async init() {
    const dir = this.wasmDir;
    const gluePath = path.join(dir, 'rime_console.js');
    const wasmPath = path.join(dir, 'rime_console.wasm');

    if (!fs.existsSync(gluePath)) {
      throw new Error(`rime_console.js not found in ${dir}`);
    }
    if (!fs.existsSync(wasmPath)) {
      throw new Error(`rime_console.wasm not found in ${dir}`);
    }

    global.window = {
      location: { pathname: dir + '/' },
      encodeURIComponent,
    };
    global.document = { currentScript: { src: gluePath } };
    global.XMLHttpRequest = makeFakeXHR();

    const Module = {
      locateFile: (p) => path.join(dir, p),
      wasmBinary: new Uint8Array(fs.readFileSync(wasmPath)),
      print: (s) => { if (this.verbose) process.stdout.write('[rime] ' + s + '\n'); },
      printErr: (s) => { if (this.verbose) process.stderr.write('[rime] ' + s + '\n'); },
      noInitialRun: true,
      noExitRuntime: true,
    };

    let resolveReady;
    const ready = new Promise((r) => { resolveReady = r; });
    Module.onRuntimeInitialized = () => resolveReady();

    const enc = this._enc;
    Module.preRun = [
      () => {
        const patch = SCHEMA_PATCH(this.schema);
        const bytes = enc.encode(patch);
        try {
          Module.FS_createPath('/', 'data', true, true);
        } catch (_) {}
        try {
          Module.FS_createDataFile('/data', 'default.custom.yaml', bytes, true, true, false);
        } catch (e) {
          if (this.verbose) process.stderr.write('[rime-api] default.custom.yaml write failed: ' + e + '\n');
        }
      },
    ];

    const src = fs.readFileSync(gluePath, 'utf8');
    new Function('Module', src)(Module);

    await ready;

    this._module = Module;

    global.window.rime_callback = (s) => {
      let p;
      try { p = JSON.parse(s); } catch (_) { p = { type: 'raw', text: s }; }
      this._onCallback(p);
    };

    try {
      Module.init();
    } catch (e) {
      if (this.verbose) process.stderr.write('[rime-api] Module.init() threw (ignored): ' + e + '\n');
    }

    this._callbacks = [];
    this._ready = true;
    return this;
  }

  _onCallback(payload) {
    this._callbacks.push(payload);
  }

  _send(key) {
    this._callbacks = [];
    this._module.input(this._enc.encode(key));
  }

  _sendSequence(keys) {
    this._callbacks = [];
    for (const k of keys) {
      this._module.input(this._enc.encode(k));
    }
  }

  _lastComposing() {
    for (let i = this._callbacks.length - 1; i >= 0; i--) {
      if (this._callbacks[i].type === 'composing') return this._callbacks[i];
    }
    return null;
  }

  _allCommits() {
    return this._callbacks
      .filter((c) => c.type === 'commit')
      .map((c) => c.text)
      .join('');
  }

  _clearComposition() {
    this._send('{Escape}');
  }

  async candidates(pinyin) {
    if (!this._ready) throw new Error('Rime not initialised. Call init() first.');
    return this._enqueue(() => {
      this._clearComposition();
      this._sendSequence(pinyin);
      const comp = this._lastComposing();
      this._clearComposition();
      if (!comp) {
        return { input: pinyin, candidates: [] };
      }
      return {
        input: comp.input,
        candidates: (comp.cand || []).map((c) => ({
          text: c.text,
          comment: c.comment || '',
        })),
        page: comp.page_no || 0,
        isLastPage: !!comp.last_page,
        highlightIndex: comp.index || 0,
      };
    });
  }

  async translate(pinyin, options = {}) {
    if (!this._ready) throw new Error('Rime not initialised. Call init() first.');
    const index = options.index != null ? options.index : 0;
    return this._enqueue(() => {
      this._clearComposition();
      this._callbacks = [];
      for (const ch of pinyin) {
        this._module.input(this._enc.encode(ch));
      }
      this._module.input(this._enc.encode(String(index + 1)));
      const text = this._allCommits();
      this._clearComposition();
      return { text };
    });
  }

  _enqueue(fn) {
    const next = this._queue.then(fn, fn);
    this._queue = next.catch(() => {});
    return next;
  }

  close() {
    this._ready = false;
    this._module = null;
    delete global.window;
    delete global.document;
    delete global.XMLHttpRequest;
  }
}

Rime.create = async function (options) {
  const rime = new Rime(options);
  await rime.init();
  return rime;
};

module.exports = Rime;
